"""create initial tables

Revision ID: cc6d9b1ffbc7
Revises: 
Create Date: 2026-04-16 15:47:35.818457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'cc6d9b1ffbc7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_params',
                    sa.Column('id', sa.SmallInteger(), nullable=False),
                    sa.Column('wind_speed', sa.Float(), nullable=False),
                    sa.Column('wind_direction', sa.Float(), nullable=False),
                    sa.Column('stability_class', sa.String(), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('substances',
                    sa.Column('id', sa.SmallInteger(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('short_name', sa.String(), nullable=False),
                    sa.Column('mcl', sa.Float(), nullable=False),
                    sa.Column('density', sa.Float(), nullable=False),
                    sa.Column('settling_velocity', sa.Float(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_substances_id'), 'substances', ['id'], unique=False)
    op.create_index(op.f('ix_substances_name'), 'substances', ['name'], unique=True)
    op.create_index(op.f('ix_substances_short_name'), 'substances', ['short_name'], unique=True)
    op.create_table('sources',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('type', sa.Enum('point', 'line', 'polygon', name='sourcetypeenum'), nullable=False),
                    sa.Column('latitude', sa.Float(), nullable=False),
                    sa.Column('longitude', sa.Float(), nullable=False),
                    sa.Column('height', sa.Float(), nullable=False),
                    sa.Column('emission_rate', sa.Float(), nullable=False),
                    sa.Column('substance_id', sa.SmallInteger(), nullable=False),
                    sa.Column('coordinates', sa.JSON(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['substance_id'], ['substances.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_sources_created_at'), 'sources', ['created_at'], unique=False)
    op.create_index(op.f('ix_sources_id'), 'sources', ['id'], unique=False)
    op.create_index(op.f('ix_sources_name'), 'sources', ['name'], unique=False)
    op.create_index(op.f('ix_sources_type'), 'sources', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sources_type'), table_name='sources')
    op.drop_index(op.f('ix_sources_name'), table_name='sources')
    op.drop_index(op.f('ix_sources_id'), table_name='sources')
    op.drop_index(op.f('ix_sources_created_at'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_substances_short_name'), table_name='substances')
    op.drop_index(op.f('ix_substances_name'), table_name='substances')
    op.drop_index(op.f('ix_substances_id'), table_name='substances')
    op.drop_table('substances')
    op.drop_table('simulation_params')
    # ### end Alembic commands ###
