"""added sun_brightness and cloud_density column in simulation_params

Revision ID: f62ec9fcff81
Revises: 8f2abe3a6d95
Create Date: 2026-05-16 15:02:27.131728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f62ec9fcff81'
down_revision: Union[str, Sequence[str], None] = '8f2abe3a6d95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulation_params', sa.Column('sun_brightness', sa.Float(), nullable=False))
    op.add_column('simulation_params', sa.Column('cloud_density', sa.SmallInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulation_params', 'cloud_density')
    op.drop_column('simulation_params', 'sun_brightness')
    # ### end Alembic commands ###
